# Numpy
https://numpy.org/

In [4]:
import numpy as np

In [5]:
x = np.array([2,5,10,20])
x

array([ 2,  5, 10, 20])

In [6]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
y = np.array([[1,2], [3,4], [5,6], [7, 8]])
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
# imprimindo somente a primeira linha do array y
y[0:1]

array([[1, 2]])

In [15]:
# imprimindo somente a primeira linha do array y 
y[:1]

array([[1, 2]])

In [20]:
# imprimindo os elementos da primeira coluna
y[:2, :1]

array([[1],
       [3]])

## função arange
https://numpy.org/doc/stable/user/basics.creation.html

In [21]:
# criando um array com valores sequenciais de 0~9
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# criando um array com valores sequenciais de 5~9
b = np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [25]:
# array contendo números sequenciais de 0~4, do tipo float
c = np.arange(5,dtype=float)
c

array([0., 1., 2., 3., 4.])

In [29]:
# alterando o valor do incremento para 2
d = np.arange(0, 10, 2)
d

array([0, 2, 4, 6, 8])

## função reshape 
https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

In [34]:
# organizando um array de 12 elementos (valores: 0~11) na forma de uma matriz de 3 linhas por 4 colunas
e = np.arange(12).reshape(3,4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
e.shape

(3, 4)

In [40]:
# "Python, calcule o numero de linhas" POR 2 colunas
f = np.arange(12).reshape(-1,2)
f

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [41]:
f.shape

(6, 2)

In [42]:
# 2 linhas por "Python, calcule o numero de colunas"...
g = np.arange(12).reshape(2,-1)
g

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [43]:
g.shape

(2, 6)

In [44]:
# Organizando os dados da seguinte forma:  
# 2 linhas, X colunas. Cada elemento deve ser uma matriz 2x2. 

h = np.arange(16).reshape(2,-1, 2,2)
h

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [45]:
h.shape

(2, 2, 2, 2)