# Introdução Criação de Tensores
https://colab.research.google.com/drive/1uVf9_WmfyrkkA6eDW_NX8-1htCopFFZ8?authuser=1


In [16]:
import tensorflow as tf

## Constant 

In [17]:
# https://www.tensorflow.org/api_docs/python/tf/constant
const_a = tf.constant( [1, 2, 3, 4] )
const_a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [18]:
const_b = tf.constant( [1, 2, 3, 4], dtype=tf.float32)
const_b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [21]:
const_c = tf.constant( [1, 2, 3, 4], shape=[2,2], dtype=tf.float32)
const_c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [22]:
const_a.dtype

tf.int32

In [23]:
const_a.ndim

1

In [24]:
const_a.numpy()

array([1, 2, 3, 4])

In [25]:
const_a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

## Variable Tensor

In [27]:
var_1 = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [28]:
var_2 = tf.Variable(tf.zeros([2,3]))
var_2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [29]:
var_3 = tf.Variable(tf.ones_like(var_1))
var_3

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [30]:
var_4 = tf.Variable(tf.zeros_like(var_1))
var_4

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [31]:
print("Valores de var_1:",var_1.read_value())

Valores de var_1: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [32]:
novo_valor=[[1,2,3],[4,5,6]]
var_1.assign(novo_valor)
print("Novos valores de var_1:",var_1.read_value())

Novos valores de var_1: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
