In [1]:
import tensorflow as tf

# Create

In [2]:
zeros_a = tf.zeros(shape=[2,3], dtype=tf.int32)
zeros_a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [4]:
ones_a = tf.ones(shape=[4,4], dtype=tf.float32)
ones_a

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [5]:
zeros_b = tf.zeros_like(ones_a)
zeros_b

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [7]:
ones_b = tf.zeros_like(zeros_a)
ones_b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [10]:
fill_a = tf.fill([5,3],9)
fill_a

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])>

In [11]:
# http://www.portalaction.com.br/probabilidades/62-distribuicao-normal
tfnormal = tf.random.normal([5,5], mean=3, stddev=1, seed=1)
tfnormal

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[2.1886818, 4.4845986, 3.0653293, 0.5572958, 3.0992484],
       [3.5912242, 3.592823 , 0.8770704, 2.2771027, 2.9437296],
       [3.6435447, 2.7356758, 4.856633 , 3.5678418, 2.6171641],
       [1.5146567, 4.261771 , 2.974694 , 2.7353704, 4.532814 ],
       [1.2570229, 2.562107 , 2.43399  , 3.3206692, 4.132831 ]],
      dtype=float32)>

# Slicing

In [13]:
#### criando um array com 5 elementos (1 dimensao)
v = [1,2,3,4,5,6]
t1 = tf.convert_to_tensor(v)
t1

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [16]:
# extraindo 
ts = t1[0:2]
ts

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [21]:
ts = t1[-3:]
ts

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [22]:
# um tensor de 2 dimensoes
v2 = [ [0,1,2],
       [3,4,5],
       [6,7,8]
     ]
t2 = tf.convert_to_tensor(v2)
t2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [25]:
# slicing 
t2[0:2, 0:2]

# por que nao imprime os valores??

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [3, 4]])>

In [27]:
# usando tf.slice

tf.slice(t2, begin=[0,1], size=[2,2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

## Concat


In [29]:
a1 = [ [10, 11,12], 
       [13, 14, 15]]

a2 = [ [20, 21, 22],
       [23, 24, 25]]

In [32]:
x = tf.concat([a1, a2], 0)
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [13, 14, 15],
       [20, 21, 22],
       [23, 24, 25]])>

In [33]:
x = tf.concat([a1, a2], 1)
x

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 20, 21, 22],
       [13, 14, 15, 23, 24, 25]])>

In [34]:
#verificando se x é uma instancia de Tensor
isinstance(x, tf.Tensor)

True